CREATE TABLE "GCG_6084_NOTES"(
 "NID" IDENTITY DEFAULT '0' CONSTRAINT "UK_NID" UNIQUE USING 0,
 "PART" CHAR(20) NOT NULL,
 "LOC" CHAR(2) NOT NULL,
 "GSUSER" CHAR(8),
 "CREATE_DT" DATETIME,
 "NOTES" LONGVARCHAR,
 "EXPIRE_DT" DATE );
